# Generated by Django 3.0.7 on 2020-08-23 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('directoryId', models.IntegerField(serialize=False)),
                ('name', models.TextField()),
                ('shortName', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('version', models.TextField(unique=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ElementDirectory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('body', models.TextField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Directory')),
            ],
        ),
    ]
