# Generated by Django 3.0.7 on 2020-08-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20200824_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='directoryId',
            field=models.IntegerField(default=1),
        ),

        migrations.AlterUniqueTogether(
            name='directory',
            unique_together={('directoryId', 'version')},
        ),
    ]
